# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.models.pagespeed_test_check_rate import PagespeedTestCheckRate

class TestPagespeedTestCheckRate(unittest.TestCase):
    """PagespeedTestCheckRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagespeedTestCheckRate(self):
        """Test PagespeedTestCheckRate"""
        # inst = PagespeedTestCheckRate()

if __name__ == '__main__':
    unittest.main()
