# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.api.heartbeat_api import HeartbeatApi


class TestHeartbeatApi(unittest.TestCase):
    """HeartbeatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HeartbeatApi()

    def tearDown(self) -> None:
        pass

    def test_create_heartbeat_test(self) -> None:
        """Test case for create_heartbeat_test

        Create a heartbeat check
        """
        pass

    def test_delete_heartbeat_test(self) -> None:
        """Test case for delete_heartbeat_test

        Delete a heartbeat check
        """
        pass

    def test_get_heartbeat_test(self) -> None:
        """Test case for get_heartbeat_test

        Retrieve a heartbeat check
        """
        pass

    def test_list_heartbeat_tests(self) -> None:
        """Test case for list_heartbeat_tests

        Get all heartbeat checks
        """
        pass

    def test_update_heartbeat_test(self) -> None:
        """Test case for update_heartbeat_test

        Update a heartbeat check
        """
        pass


if __name__ == '__main__':
    unittest.main()
