# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.api.pagespeed_api import PagespeedApi


class TestPagespeedApi(unittest.TestCase):
    """PagespeedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PagespeedApi()

    def tearDown(self) -> None:
        pass

    def test_create_pagespeed_test(self) -> None:
        """Test case for create_pagespeed_test

        Create a pagespeed check
        """
        pass

    def test_delete_pagespeed_test(self) -> None:
        """Test case for delete_pagespeed_test

        Delete a pagespeed check
        """
        pass

    def test_get_pagespeed_test(self) -> None:
        """Test case for get_pagespeed_test

        Retrieve a pagespeed check
        """
        pass

    def test_list_pagespeed_test_history(self) -> None:
        """Test case for list_pagespeed_test_history

        Get all pagespeed check history
        """
        pass

    def test_list_pagespeed_tests(self) -> None:
        """Test case for list_pagespeed_tests

        Get all pagespeed checks
        """
        pass

    def test_update_pagespeed_test(self) -> None:
        """Test case for update_pagespeed_test

        Update a pagespeed check
        """
        pass


if __name__ == '__main__':
    unittest.main()
