# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.api.ssl_api import SslApi


class TestSslApi(unittest.TestCase):
    """SslApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SslApi()

    def tearDown(self) -> None:
        pass

    def test_create_ssl_test(self) -> None:
        """Test case for create_ssl_test

        Create an SSL check
        """
        pass

    def test_delete_ssl_test(self) -> None:
        """Test case for delete_ssl_test

        Delete an SSL check
        """
        pass

    def test_get_ssl_test(self) -> None:
        """Test case for get_ssl_test

        Retrieve an SSL check
        """
        pass

    def test_list_ssl_tests(self) -> None:
        """Test case for list_ssl_tests

        Get all SSL checks
        """
        pass

    def test_update_ssl_test(self) -> None:
        """Test case for update_ssl_test

        Update an SSL check
        """
        pass


if __name__ == '__main__':
    unittest.main()
