# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.api.maintenance_windows_api import MaintenanceWindowsApi


class TestMaintenanceWindowsApi(unittest.TestCase):
    """MaintenanceWindowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaintenanceWindowsApi()

    def tearDown(self) -> None:
        pass

    def test_create_maintenance_window(self) -> None:
        """Test case for create_maintenance_window

        Create a maintenance window
        """
        pass

    def test_delete_maintenance_window(self) -> None:
        """Test case for delete_maintenance_window

        Delete a maintenance window
        """
        pass

    def test_get_maintenance_window(self) -> None:
        """Test case for get_maintenance_window

        Retrieve a maintenance window
        """
        pass

    def test_list_maintenance_windows(self) -> None:
        """Test case for list_maintenance_windows

        Get all maintenance windows
        """
        pass

    def test_update_maintenance_window(self) -> None:
        """Test case for update_maintenance_window

        Update a maintenance window
        """
        pass


if __name__ == '__main__':
    unittest.main()
