# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.api.uptime_api import UptimeApi


class TestUptimeApi(unittest.TestCase):
    """UptimeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UptimeApi()

    def tearDown(self) -> None:
        pass

    def test_create_uptime_test(self) -> None:
        """Test case for create_uptime_test

        Create an uptime check
        """
        pass

    def test_delete_uptime_test(self) -> None:
        """Test case for delete_uptime_test

        Delete an uptime check
        """
        pass

    def test_get_uptime_test(self) -> None:
        """Test case for get_uptime_test

        Retrieve an uptime check
        """
        pass

    def test_list_uptime_test_alerts(self) -> None:
        """Test case for list_uptime_test_alerts

        Get all uptime check alerts
        """
        pass

    def test_list_uptime_test_history(self) -> None:
        """Test case for list_uptime_test_history

        Get all uptime check history
        """
        pass

    def test_list_uptime_test_periods(self) -> None:
        """Test case for list_uptime_test_periods

        Get all uptime check periods
        """
        pass

    def test_list_uptime_tests(self) -> None:
        """Test case for list_uptime_tests

        Get all uptime checks
        """
        pass

    def test_update_uptime_test(self) -> None:
        """Test case for update_uptime_test

        Update an uptime check
        """
        pass


if __name__ == '__main__':
    unittest.main()
