# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.models.monitoring_locations import MonitoringLocations

class TestMonitoringLocations(unittest.TestCase):
    """MonitoringLocations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitoringLocations:
        """Test MonitoringLocations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitoringLocations`
        """
        model = MonitoringLocations()
        if include_optional:
            return MonitoringLocations(
                data = [
                    statuscake.models.monitoring_location.MonitoringLocation(
                        description = '', 
                        ipv4 = '', 
                        ipv6 = '', 
                        region = '', 
                        region_code = '', 
                        status = 'down', )
                    ]
            )
        else:
            return MonitoringLocations(
                data = [
                    statuscake.models.monitoring_location.MonitoringLocation(
                        description = '', 
                        ipv4 = '', 
                        ipv6 = '', 
                        region = '', 
                        region_code = '', 
                        status = 'down', )
                    ],
        )
        """

    def testMonitoringLocations(self):
        """Test MonitoringLocations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
