# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from statuscake.models.uptime_tests import UptimeTests

class TestUptimeTests(unittest.TestCase):
    """UptimeTests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UptimeTests:
        """Test UptimeTests
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UptimeTests`
        """
        model = UptimeTests()
        if include_optional:
            return UptimeTests(
                data = [
                    statuscake.models.uptime_test_overview.UptimeTestOverview(
                        id = '', 
                        name = '', 
                        website_url = '', 
                        test_type = 'DNS', 
                        check_rate = 0, 
                        contact_groups = [
                            ''
                            ], 
                        paused = True, 
                        status = 'down', 
                        tags = [
                            ''
                            ], 
                        uptime = 0, )
                    ],
                metadata = statuscake.models.pagination.Pagination(
                    page = 1, 
                    per_page = 1, 
                    page_count = 1, 
                    total_count = 1, )
            )
        else:
            return UptimeTests(
                data = [
                    statuscake.models.uptime_test_overview.UptimeTestOverview(
                        id = '', 
                        name = '', 
                        website_url = '', 
                        test_type = 'DNS', 
                        check_rate = 0, 
                        contact_groups = [
                            ''
                            ], 
                        paused = True, 
                        status = 'down', 
                        tags = [
                            ''
                            ], 
                        uptime = 0, )
                    ],
                metadata = statuscake.models.pagination.Pagination(
                    page = 1, 
                    per_page = 1, 
                    page_count = 1, 
                    total_count = 1, ),
        )
        """

    def testUptimeTests(self):
        """Test UptimeTests"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
