# coding: utf-8

# flake8: noqa
"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from statuscake.models.api_error import APIError
from statuscake.models.api_response import APIResponse
from statuscake.models.api_response_data import APIResponseData
from statuscake.models.contact_group import ContactGroup
from statuscake.models.contact_group_response import ContactGroupResponse
from statuscake.models.contact_groups import ContactGroups
from statuscake.models.heartbeat_test import HeartbeatTest
from statuscake.models.heartbeat_test_overview import HeartbeatTestOverview
from statuscake.models.heartbeat_test_response import HeartbeatTestResponse
from statuscake.models.heartbeat_test_status import HeartbeatTestStatus
from statuscake.models.heartbeat_tests import HeartbeatTests
from statuscake.models.links import Links
from statuscake.models.maintenance_window import MaintenanceWindow
from statuscake.models.maintenance_window_repeat_interval import MaintenanceWindowRepeatInterval
from statuscake.models.maintenance_window_response import MaintenanceWindowResponse
from statuscake.models.maintenance_window_state import MaintenanceWindowState
from statuscake.models.maintenance_windows import MaintenanceWindows
from statuscake.models.monitoring_location import MonitoringLocation
from statuscake.models.monitoring_location_status import MonitoringLocationStatus
from statuscake.models.monitoring_locations import MonitoringLocations
from statuscake.models.pagespeed_test import PagespeedTest
from statuscake.models.pagespeed_test_check_rate import PagespeedTestCheckRate
from statuscake.models.pagespeed_test_history import PagespeedTestHistory
from statuscake.models.pagespeed_test_history_result import PagespeedTestHistoryResult
from statuscake.models.pagespeed_test_region import PagespeedTestRegion
from statuscake.models.pagespeed_test_response import PagespeedTestResponse
from statuscake.models.pagespeed_test_stats import PagespeedTestStats
from statuscake.models.pagespeed_test_throttling import PagespeedTestThrottling
from statuscake.models.pagespeed_tests import PagespeedTests
from statuscake.models.pagination import Pagination
from statuscake.models.ssl_test import SSLTest
from statuscake.models.ssl_test_check_rate import SSLTestCheckRate
from statuscake.models.ssl_test_flags import SSLTestFlags
from statuscake.models.ssl_test_mixed_content import SSLTestMixedContent
from statuscake.models.ssl_test_response import SSLTestResponse
from statuscake.models.ssl_tests import SSLTests
from statuscake.models.uptime_test import UptimeTest
from statuscake.models.uptime_test_alert import UptimeTestAlert
from statuscake.models.uptime_test_alerts import UptimeTestAlerts
from statuscake.models.uptime_test_check_rate import UptimeTestCheckRate
from statuscake.models.uptime_test_history import UptimeTestHistory
from statuscake.models.uptime_test_history_result import UptimeTestHistoryResult
from statuscake.models.uptime_test_overview import UptimeTestOverview
from statuscake.models.uptime_test_period import UptimeTestPeriod
from statuscake.models.uptime_test_periods import UptimeTestPeriods
from statuscake.models.uptime_test_processing_state import UptimeTestProcessingState
from statuscake.models.uptime_test_response import UptimeTestResponse
from statuscake.models.uptime_test_status import UptimeTestStatus
from statuscake.models.uptime_test_type import UptimeTestType
from statuscake.models.uptime_tests import UptimeTests
