# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from statuscake.models.maintenance_window_repeat_interval import MaintenanceWindowRepeatInterval
from statuscake.models.maintenance_window_state import MaintenanceWindowState
from typing import Optional, Set
from typing_extensions import Self

class MaintenanceWindow(BaseModel):
    """
    MaintenanceWindow
    """ # noqa: E501
    id: StrictStr = Field(description="Maintenance window ID")
    name: StrictStr = Field(description="Name of the maintenance window")
    end_at: datetime = Field(description="End of the maintenance window (RFC3339 format)")
    repeat_interval: MaintenanceWindowRepeatInterval
    start_at: datetime = Field(description="Start of the maintenance window (RFC3339 format)")
    state: MaintenanceWindowState
    tags: List[StrictStr] = Field(description="List of tags used to include matching uptime checks in this maintenance window")
    tests: List[StrictStr] = Field(description="List of uptime check IDs explicitly included in this maintenance window")
    timezone: StrictStr = Field(description="Standard [timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) associated with this maintenance window")
    __properties: ClassVar[List[str]] = ["id", "name", "end_at", "repeat_interval", "start_at", "state", "tags", "tests", "timezone"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaintenanceWindow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaintenanceWindow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "end_at": obj.get("end_at"),
            "repeat_interval": obj.get("repeat_interval"),
            "start_at": obj.get("start_at"),
            "state": obj.get("state"),
            "tags": obj.get("tags"),
            "tests": obj.get("tests"),
            "timezone": obj.get("timezone")
        })
        return _obj


