# coding: utf-8

"""
    StatusCake API

    StatusCake API endpoints to manage monitoring resources.  # Authentication  Documentation on API authentication can be found [here](https://developers.statuscake.com/guides/api/authentication).  # Ratelimiting  Documentation on API ratelimiting can be found [here](https://developers.statuscake.com/guides/api/ratelimiting).  # Errors  Documentation on error handling can be found [here](https://developers.statuscake.com/guides/api/errors).  # Handling Input Parameters  Documentation on input parameters, including how to pass arrays to API endpoints can be found [here](https://developers.statuscake.com/guides/api/parameters). 

    The version of the OpenAPI document: 1.2.0
    Contact: support@statuscake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UptimeTestCheckRate(int, Enum):
    """
    Number of seconds between checks
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_30 = 30
    NUMBER_60 = 60
    NUMBER_300 = 300
    NUMBER_900 = 900
    NUMBER_1800 = 1800
    NUMBER_3600 = 3600
    NUMBER_86400 = 86400

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UptimeTestCheckRate from a JSON string"""
        return cls(json.loads(json_str))


